Site BackEnd/E_Commerce_site/E_Commerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('order/', include('order.urls')),
    path('account/', include('user.urls')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Site BackEnd/E_Commerce_site/products/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('products/', products, name='products'),

    # Product details and reviews routes
    path('view-details/<str:pk>/', view_details, name='view_details'),
    path('review/<str:pk>/', review, name='review'),
    path('replay/<str:pk>/', replay, name='replay'),
    path('get-all-review/<str:pk>/', show_all_reviews, name='show_all_reviews'),

    # Cart route
    path('cart/', cart, name='cart'),

]

Site BackEnd/E_Commerce_site/user/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    path('redirect-user/base-location/', redirect_origin, name='redirect_origin'),
    path('logout/', logout_user, name='logout'),

    # Staff Area

    # Product Handler

    path('staff-main-1/', staff_main1, name='staff_main1'),
    path('pending-orders/', pending_orders, name='pending_orders'),
    path('pending-order-action/', pending_order_action, name='pending_order_action'),

    # Product Adder

    path('staff-main-2/', staff_main2, name='staff_main2'),
    path('add-edit-products/', add_products, name='add_products'),
    path('add-edit-products/<str:pk>/', edit_products, name='edit_products'),

    # Normal & unregistered user

    path('', account, name='account'),
    path('order-history/', order_history, name='order_history'),
    path('query-order-history/', query_order_history, name='query_order_history'),
    path('save-wishlist-item/', save_wishlist_item, name='save_wishlist_item'),
    path('check-wishlist-item-availability/', check_product_availability, name='check_product_availability'),
    path('remove-wishlist-item/', remove_wishlist_item, name='remove_wishlist_item'),
    path('wishlist/', wishlist, name='wishlist'),
    path('transaction/', transactions, name='transaction'),

    # Admin

    path('admin/', dashboard, name='admin_dashboard'),
    path('statistics/', statistics, name='statistics'),
    path('admin/product-list/', admin_product_list, name='admin_product_list'),
    path('admin/orders/', admin_orders, name='admin_orders'),
    path('admin/add-edit-product/', admin_add_product, name='admin_add_product'),
    path('admin/add-edit-product/<str:pk>/', admin_edit_product, name='admin_edit_product'),
    path('admin/transactions/', admin_transactions, name='admin_transactions'),








]

Site BackEnd/E_Commerce_site/products/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


# Category model
class Category(models.Model):

    """Category model"""

    category_name = models.CharField(max_length=30)


# Offers model

class DiscountReason(models.Model):

    """Offers and discount model"""

    discount_reason = models.CharField(max_length=30)


# Product model
class Product(models.Model):

    """Product model"""

    # Product details
    product_title = models.CharField(max_length=200)
    product_code = models.CharField(max_length=15)
    product_price = models.IntegerField()
    product_category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    color_type = models.CharField(max_length=100)
    yarn_type = models.CharField(max_length=100)
    yarn_count = models.IntegerField()
    brand = models.CharField(max_length=30)
    product_in_stock = models.BooleanField(default=True)
    product_tags = models.CharField(max_length=300)
    product_added_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=1)
    product_last_update = models.DateTimeField(auto_now_add=True)
    product_type = models.CharField(max_length=40, null=True, blank=True)

    # Product images
    product_primary_image = models.ImageField(upload_to='product_primary_images/')

    # Seo section
    product_more_information = models.CharField(max_length=200)
    product_search_keyword = models.CharField(max_length=400)

    # Offer Section
    on_discount = models.BooleanField(default=False)
    discount_percentage = models.IntegerField(default=0)
    discount_price = models.IntegerField(default=0)
    discount_reason = models.ForeignKey(DiscountReason, on_delete=models.DO_NOTHING, null=True, blank=True)
    discount_expiry = models.DateTimeField(null=True, blank=True)

    wish_count = models.IntegerField(default=0)

    def __str__(self):
        return f'({self.id}), {self.product_title}'


# Product images model
class ProductImages(models.Model):

    """Product image model to store multiple images"""

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images/')
    image_alt_tag = models.CharField(max_length=30)


# Cart model
class Cart(models.Model):

    """Cart model, I've covered cart functionality in front end , so this model is unused,
        but still I'm keeping it for future reference"""

    cart_items = models.CharField(max_length=400)
    cart_person_ip = models.GenericIPAddressField()
    cart_person = models.OneToOneField(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    cart_items_price = models.IntegerField()
    cart_added_date = models.DateTimeField(auto_now_add=True)
    cart_id = models.UUIDField(auto_created=True)


# Wishlist model

class WishList(models.Model):

    """Wishlist model to store wished products, only for registered users"""

    wishlist_items = models.CharField(max_length=100)
    wisher_person_ip = models.GenericIPAddressField()
    wisher_person = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)


# Reviews and replays

class Review(models.Model):

    """Product review model"""

    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    review_text = models.CharField(max_length=500)
    rating = models.IntegerField(default=1)


class ReviewReply(models.Model):

    """Product review replies model"""

    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    replay_text = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

Site BackEnd/E_Commerce_site/user/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models


class UserManager(BaseUserManager):

    """Abstracting BaseUserManager for creating custom user system and
        custom login/superuser creating system."""

    def create_user(self, name, phone, email, password=None):
        if not name:
            raise ValueError('Name is required')
        if not phone:
            raise ValueError('Phone is required')
        if not email:
            raise ValueError('Email is required')
        user = self.model(
            name=name,
            phone=phone,
            email=email
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, name, phone, email, password=None):
        user = self.create_user(
            name=name,
            phone=phone,
            email=email,
            password=password
        )
        user.is_superuser = True
        user.is_staff = True
        user.is_admin = True

        user.save(using=self._db)
        return user


class User(AbstractBaseUser):

    """Abstracting BaseUser model to add custom fields as per requirements"""

    first_name = models.CharField(verbose_name='first_name', max_length=22, blank=True, null=True)
    last_name = models.CharField(verbose_name='last_name', max_length=22, blank=True, null=True)
    name = models.CharField(verbose_name='Name', max_length=22)
    email = models.EmailField(verbose_name='Email Address', max_length=50, unique=True, null=True, blank=True)
    phone = models.CharField(verbose_name='Phone Number', max_length=11, unique=True)
    ip = models.GenericIPAddressField(verbose_name='Ip address', null=True, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics/', null=True, blank=True)

    # permissions

    # staff permissions
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_order_handler = models.BooleanField(default=False)
    is_product_adder = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'phone']

    objects = UserManager()

    def save(self, commit=True, *args, **kwargs):  # Edited

        if commit:
            if self.first_name and self.last_name:
                self.name = f'{self.first_name} {self.last_name}'

            super().save()

    def __str__(self):
        return self.name

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True


# Model for profile picture


class Profile(models.Model):
    picture = models.ImageField(upload_to='profile-images/')


# Address model for saving addresses

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=30)
    address = models.CharField(max_length=40)
    zipcode = models.IntegerField()

Site BackEnd/E_Commerce_site/products/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.decorators.csrf import csrf_exempt
from .models import *
from user.algorithms import router
from .algorithms import *
from django.db.models import Q
from django.middleware.csrf import get_token


# Base Home
def home(request):

    """Landing page view, with new arrival products on display"""

    # Router definition -> It determines user type and tells if the user is authenticated for accessing this page
    request_action = router(request, {'is_order_handler': False, 'is_product_adder': False, 'is_admin': False,
                                      'is_user': True})

    if not request_action[0] and len(request_action) < 3:
        return redirect(request_action[1])

    products = Product.objects.filter(product_in_stock=True).order_by('product_last_update')[:20]
    categories = Category.objects.all()
    context = {
        'products': products,
        'categories': categories
    }
    return render(request, 'index.html', context)


# Products Page
def products(request):

    """Products page view , with filtering and searching capability"""

    # Router definition -> It determines user type and tells if the user is authenticated for accessing this page
    request_action = router(request, {'is_order_handler': False, 'is_product_adder': False, 'is_admin': False,
                                      'is_user': True})
    if not request_action[0] and len(request_action) < 3:
        return redirect(request_action[1])

    # If request method is post filter out products by search query
    if request.method == 'POST':
        query_data = request.POST

        # Calling out filter function from products.algorithms to filter the products
        products_list = filter_products(query_data)

        # Generating new csrf token for another post request --> Supports simultaneous request
        new_token = get_token(request)

        context = {
            'template': render_to_string('products_filter_template.html', context={'products': products_list},
                                         request=request),
            'token': new_token
        }
        return JsonResponse(context)

    # If request is GET and there is a query string filter out by query string then return the products anyway.

    query = ''
    if 's' in request.GET:
        query = request.GET['s']

    category = Category.objects.filter(category_name__icontains=query)
    reasons = DiscountReason.objects.filter(discount_reason__icontains=query)

    products_list = Product.objects.filter(
        Q(product_title__icontains=query) | Q(brand__icontains=query) | Q(product_tags__icontains=query) |
        Q(product_search_keyword__icontains=query) | Q(product_more_information__icontains=query) |
        Q(product_category__in=category) | Q(discount_reason__in=reasons)

    )

    # We want all products by query when query string is given
    if 's' not in request.GET:
        products_list = products_list.filter(product_in_stock=True)

    # Search keywords for search suggestions
    search_keywords = Product.objects.all()

    # For filtering purpose
    categories = Category.objects.all()
    reasons = DiscountReason.objects.all()

    context = {
        'products': products_list,
        'query': query,
        'query_string': True if query != '' else False,
        'search_keywords': search_keywords,
        'categories': categories,
        'reasons': reasons
    }
    return render(request, 'products.html', context)


# View a product details Page
def view_details(request, pk):

    """Returns full details of a product and it's Reviews."""

    # Router definition -> It determines user type and tells if the user is authenticated for accessing this page
    request_action = router(request, {'is_order_handler': False, 'is_product_adder': False, 'is_admin': False,
                                      'is_user': True})
    if not request_action[0] and len(request_action) < 3:
        return redirect(request_action[1])

    product = Product.objects.get(pk=pk)
    query = product.product_title
    search_keywords = Product.objects.all()

    # Getting average rating of the product -> Algorithm defined in algorithms
    avg_rating = get_avg_rating(product)

    # Getting similar products
    similar_products = Product.objects.filter(
        Q(product_title__icontains=query) | Q(brand__icontains=query) | Q(product_tags__icontains=query) |
        Q(product_search_keyword__icontains=query) | Q(product_more_information__icontains=query) |
        Q(product_category__in=[product.product_category]) | Q(discount_reason__in=[product.discount_reason]))

    context = {
        'product': product,
        'search_keywords': search_keywords,
        'loop': [0, 1, 2, 3, 4],
        'similar_products': similar_products,
        'avg_rating': avg_rating,
        'avg_abs_rating': abs(avg_rating)

    }
    return render(request, 'view_details.html', context)


# Reviews and rating

# Review
def review(request, pk):

    """Saving review of a product"""

    product = Product.objects.get(pk=pk)
    rev = Review(review_text=request.POST['review_text'], user=request.user, product=product,
                 rating=int(request.POST['rating']))
    context = {
        'product': product,
        'loop': [0, 1, 2, 3, 4],
        'limiter': True
    }
    rev.save()

    # We can add chatGPT here to automatically generate a review replay with concise context -> But now forget it

    template = render_to_string('review_template.html', context=context, request=request)
    new_token = get_token(request)

    return JsonResponse({'template': template, 'token': new_token})


# Review Reply
def replay(request, pk):

    """Reply on a Review"""

    rev = Review.objects.get(pk=pk)
    product = rev.product
    rep = ReviewReply(replay_text=request.POST['replay_text'], user=request.user, review=rev)
    rep.save()
    context = {
        'product': product,
        'loop': [0, 1, 2, 3, 4],
        'limiter': True
    }
    rev.save()
    template = render_to_string('review_template.html', context=context, request=request)
    new_token = get_token(request)

    return JsonResponse({'template': template, 'token': new_token})


# All Review
def show_all_reviews(request, pk):

    """Show all review of a product"""

    product = Product.objects.get(pk=pk)
    context = {
        'product': product,
        'loop': [0, 1, 2, 3, 4],
        'limiter': False
    }
    return render(request, 'review_template.html', context)


# Cart and wishlist


# Cart
@csrf_exempt
def cart(request):

    """Cart functionalities is handled on the frontEnd side"""

    # Router definition -> It determines user type and tells if the user is authenticated for accessing this page
    request_action = router(request, {'is_order_handler': False, 'is_product_adder': False, 'is_admin': False,
                                      'is_user': True})
    if not request_action[0] and len(request_action) < 3:
        return redirect(request_action[1])
    
    products = Product.objects.all()

    return render(request, 'cart.html', {'products': products})


# Wishlist
def wishlist(request):

    """Wishlist functionalities is handled on the frontEnd side"""

    # Router definition -> It determines user type and tells if the user is authenticated for accessing this page
    request_action = router(request, {'is_order_handler': False, 'is_product_adder': False, 'is_admin': False,
                                      'is_user': True})
    if not request_action[0] and len(request_action) < 3:
        return redirect(request_action[1])

    return render(request, 'wishlist.html')

Site BackEnd/E_Commerce_site/templates/login.html
{% extends 'index.html' %}
{% load static %}

    {% block title %} Login {% endblock title %}

    {% block jsfiles %}
        <script src="{% static 'js/login_registration.js' %}"></script>
    {% endblock jsfiles %}

    {% block cssfiles %}
        <link rel="stylesheet" href="{% static 'css/products.css' %}">
        <link rel="stylesheet" href="{% static 'css/login.css' %}">
    {% endblock cssfiles %}


    {% block nav_2 %} {% endblock nav_2 %}

    {% block container %}

        <div class="login-card">

            <form id="login-form">
                {% csrf_token %}
                <p class="title">Sign in</p>

                <div class="input">
                    <span>E-mail</span>
                    <input type="email" id="email" placeholder="Enter email">
                </div>

                <div class="input login-password">
                    
                    <div class="pass-and-forgot-pass">
                        <span>Password</span>
                        <a href="#" class="forgot-pass">Forgot Password</a>
                    </div>

                    <div class="password-container">
                        <input type="password" id="password-input" placeholder="Enter password">
                        <span class="password-toggle-icon" onclick="togglePasswordVisibility()">
                          <i class="fa fa-eye-slash" id="password-toggle-icon"></i>
                        </span>
                    </div>
                    <script>
                        function togglePasswordVisibility() {
                            var passwordInput = document.getElementById("password-input");
                            var passwordToggleIcon = document.getElementById("password-toggle-icon");

                            if (passwordInput.type === "password") {
                                passwordInput.type = "text";
                                passwordToggleIcon.className = "fa fa-eye";
                            } else {
                                passwordInput.type = "password";
                                passwordToggleIcon.className = "fa fa-eye-slash";
                            }
                        }
                    </script>


                </div>

                <button class="login-btn" type="submit">
                    <span id="l-t">Login</span> <i id="l-i" class="fa fa-spinner fa-spin d-none"></i>
                </button>

            </form>

            <div class="or-border">
                <div class="line"></div>
                <small>OR</small>
                <div class="line"></div>
            </div>

            <button class="sign-with-google">

                <div class="icon">
                    <img src="{% static 'img/google-logo.png' %}" alt="">
                </div>

                <p>Continue with Google</p>

                <div></div>

            </button>
            <button class="sign-with-facebook">

                <div class="icon">
                    <i class="fab fa-facebook"></i>
                </div>

                <p>Continue with Facebook</p>

                <div></div>

            </button>

            <div class="register-link">
                <p>Don't have an account? </p>
                <a href="#"> Register now</a>
            </div>

        </div>

    {% endblock container %}

    {% block footer_top %} {% endblock footer_top %}

Site BackEnd/E_Commerce_site/templates/products_filter_template.html
{% if products %}
{% for product in products %}
<li>

    <div class="product-card">

        <div class="product-card-and-view-mask">

                 {% if not product.product_in_stock %}
                    <div class="extra-msg out">
                        <p>Out of stock</p>
                    </div>
                 {% elif product.on_discount %}
                    <div class="extra-msg offer">
                        <p>{{product.discount_reason.discount_reason |upper}} <i>{{product.discount_percentage}}% OFF</i></p>
                    </div>
                 {% endif %}
                <a href="{% url 'view_details' product.id %}">
                    <div class="view-mask">
                        <p>View Details</p>
                    </div>
                </a>

            <div class="p-c-img">
                <img draggable="false" src="{{product.product_primary_image.url}}" alt="{{product.product_search_keyword}}">
            </div>

        </div>



        <div class="line"></div>
        {% if product.on_discount %}
             <div class="price">
                <p class="n-price">${{product.product_price}}</p>
                 <p class="offer-price">$<span id="p_price-{{product.id}}">{{product.discount_price}}</span></p>
             </div>
        {% else %}
             <div class="price">
                <p>$<span id="p_price-{{product.id}}">{{product.product_price}}</span></p>

             </div>
        {% endif %}
        <p class="title" id="p_title-{{product.id}}">{{product.product_title}}</p>
        <input type="hidden" id="p_status-{{product.id}}" value="{{product.product_in_stock}}">

        <div class="p-c-btns">
            {% if product.product_in_stock %}
                <button class="add-to-cart" onclick="add_to_cart( {{product.id}}, `{{request.user}}`, get_size_quantity(false) )">Add to cart</button>
            {% else %}
                 <button class="add-to-cart" style="background:gray; opacity:.6; cursor:not-allowed;" disabled>Out of stock</button>
            {% endif %}
            <button class="add-to-wishlist" onclick="add_to_wishlist({{product.id}}, '{{request.user}}')">
                <i class="far fa-heart"></i>
            </button>
        </div>
    </div>

</li>
{% endfor %}
{% else %}
<p style="font-weight:500">No products Found !</p>
{% endif %}

Site BackEnd/E_Commerce_site/templates/redirect_user_base_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Redirecting</title>
    <script>
      let ls = localStorage
      let url = '';

      window.location.href = ls.getItem('redirect_url')

    </script>
</head>
<body>
  <p>Redirecting . . .</p>
</body>
</html>

Site BackEnd/E_Commerce_site/templates/review_template.html
{% load static %}


{% for review in product.review_set.all %}

  {% if limiter and forloop.counter < 3 %}
     <div class="review">
    <div class="left">
    {% if review.user.profile_pic %}
        <img src="{{review.user.profile_pic.url}}" alt="{{review.user.name}} picture">
    {% else %}
        <img src="{% static 'img/person.png' %}" alt="Default person picture">
    {% endif %}
    </div>
    <div class="right" style="width:100%">
    <p class="name">{{review.user.name}}</p>

    <div class="rates">
        {% for i in loop %}

            {% if forloop.counter <= review.rating %}
                <span class="fa fa-star checked"></span>
            {% else %}
                <span class="fa fa-star" style="opacity:.7"></span>
            {% endif %}

        {% endfor %}


    </div>

    <small>{{review.review_text}}</small>

    <button class="reply" onclick="document.getElementById('write-reply').style.display='flex';">Reply</button>

    <form class="write-reply" id="write-reply" r_id="{{review.id}}">
        <input type="text" name="replay_text" id="replay_text" placeholder="Write your reply">
        <button>Submit</button>
    </form>

    <div class="replys-container">
        <p class="title">
            Replays
        </p>

        {% for reply in review.reviewreply_set.all %}
            <div class="replys">

            <div class="left">

                {% if reply.user.profile_pic %}
                    <img src="{{reply.user.profile_pic.url}}" alt="{{reply.user.name}} s picture">
                {% else %}
                    <img src="{% static 'img/person.png' %}">
                {% endif %}

            </div>
            <div class="right">
                <p class="name">{{reply.user.name}}</p>

                <small>{{reply.replay_text}}</small>
            </div>
        </div>
        {% endfor %}

    </div>

</div>
</div>

  {% else %}

    <div class="review">
        <div class="left">
            {% if review.user.profile_pic %}
                <img src="{{review.user.profile_pic.url}}" alt="{{review.user.name}} picture">
            {% else %}
                <img src="{% static 'img/person.png' %}" alt="Default person picture">
            {% endif %}
        </div>
        <div class="right" style="width:100%">
            <p class="name">{{review.user.name}}</p>

            <div class="rates">
                {% for i in loop %}

                    {% if forloop.counter <= review.rating %}
                        <span class="fa fa-star checked"></span>
                    {% else %}
                        <span class="fa fa-star" style="opacity:.7"></span>
                    {% endif %}

                {% endfor %}


            </div>

            <small>{{review.review_text}}</small>

            {% if request.user.is_authenticated %}
                <button class="reply" onclick="document.getElementById('write-reply{{review.id}}').style.display='flex';">Reply</button>

                <form class="write-reply" id="write-reply{{review.id}}" r_id="{{review.id}}">
                    <input type="text"  name="replay_text" id="replay_text{{review.id}}" placeholder="Write your reply">
                    <button type="submit">Submit</button>
                </form>
            {% endif %}

            <div class="replys-container">
                <p class="title">
                    Replays
                </p>

                {% for reply in review.reviewreply_set.all %}
                    <div class="replys">

                    <div class="left">

                        {% if reply.user.profile_pic %}
                            <img src="{{reply.user.profile_pic.url}}" alt="{{reply.user.name}} s picture">
                        {% else %}
                            <img src="{% static 'img/person.png' %}">
                        {% endif %}

                    </div>
                    <div class="right">
                        <p class="name">{{reply.user.name}}</p>

                        <small>{{reply.replay_text}}</small>
                    </div>
                </div>
                {% endfor %}

            </div>

        </div>
    </div>
  {% endif %}

{% endfor %}

{% if limiter %}
<button class="show-all-reviews" onclick="show_all_reviews({{product.id}})">Show all</button>
{% endif %}

Site BackEnd/E_Commerce_site/templates/transactions.html
{% extends 'index.html' %}
{% load static %}

    {% block title %} Transactions {% endblock title %}

    {% block cssfiles %}
        <link rel="stylesheet" href="{% static 'css/products.css' %}">
        <link rel="stylesheet" href="{% static 'css/wishlist.css' %}">
        <link rel="stylesheet" href="{% static 'css/page_profile.css' %}">
        <link rel="stylesheet" href="{% static 'css/transactions.css' %}">
    {% endblock cssfiles %}

    {% block nav_2 %}{% endblock nav_2 %}

    {% block container %}

        <div class="navigator-products">

            <div class="n-p-contents">
                <a href="{% url 'home' %}}">Home > </a>
                <a href="{% url 'account' %}">Account ></a>
                <a href="{% url 'transaction' %}" style="color:gray">Transactions ></a>
            </div>

        </div>

        <!-- End Page Navigator -->


        <!-- Profile Container -->

        <div class="profile-container">

            <!-- Profile Navigation -->

            <div class="profile-nav">

                 <ul>
                    <a href="{% url 'account' %}"><li class="">Account main</li></a>
                    <a href="{% url 'order_history' %}"><li >Orders history</li></a>
                    <a href="{% url 'wishlist' %}"><li class="">My wishlist</li></a>
                    <a href="{% url 'transaction' %}" class="current-tab-profile"><li class="">Transactions</li></a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'logout' %}"><li class="">Log out</li></a>
                    {% else %}
                        <a href="{% url 'login' %}"><li class="">Log in</li></a>
                    {% endif %}
                </ul>

            </div>

            <!-- End Profile Navigation -->


            <!-- Transaction List -->

            <div class="profile-content">

                <div class="current-orders transactions">

                    <p class="title"> Transactions </p>

                    <div class="transaction-list">

                        {% for tran in transactions %}
                            <div class="item">

                                <div class="operator-logo">

                                    <img src="{% static 'img/1656227518bkash-logo-png.png' %}" alt="">

                                </div>

                                <div class="trans-id-and-amount">

                                    <p class="trans-id "> <span>Trans ID:</span> {{tran.transaction_id}}</p>
                                    <p class="trans-id"><span>Amount:</span> ${{tran.transaction_amount}}</p>

                                </div>

                                <p class="date">{{tran.transaction_date}}</p>



                                <a href="/account/query-order-history/?s={{tran.order.id}}" style="text-decoration:none">
                                    <button class="view-order-btn">
                                        View order
                                    </button>
                                </a>

                            </div>
                        {% endfor %}

                    </div>

                </div>

            </div>

            <!-- End  Transaction List  -->

        </div>

    {% endblock container %}